// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwgmcdbuyhwlcmcatnqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3Z21jZGJ1eWh3bGNtY2F0bnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzY2OTMsImV4cCI6MjA2NDYxMjY5M30.Ic47V73FuCudHwrEs7FGcLUAEWQANxBSUowD1O5SXno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);